name: Build Tauri Android Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Tauri Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add all targets
        run: |
          rustup target add \
          aarch64-linux-android \
          x86_64-linux-android

      - name: Install cargo deps
        run: |
          cargo install cargo-ndk cargo-license --locked

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
          cache-all-crates: true

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Android dependencies
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev build-essential curl wget file unzip

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up Java Environment
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install Node.js dependencies
        run: |
          pnpm install --no-frozen-lockfile

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c

      - name: Init Tauri Android
        run: |
          pnpm tauri android init
        env:
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Create App Key
        run: |
          echo "${{ secrets.APP_KEY }}" | base64 --decode > src-tauri/gen/android/upload-keystore.jks
          
          cat <<EOL > src-tauri/gen/android/keystore.properties
          storePassword=${{ secrets.STORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=upload-keystore.jks
          EOL

      - name: Configure Gradle for Signing
        run: |
          chmod +x ./scripts/gradle-sign.sh
          ./scripts/gradle-sign.sh

      - name: Build Android Release APK with Tauri
        run: |
          pnpm tauri android build
        env:
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Extract APK path
        run: |
          APK_PATH=$(find src-tauri/gen/android/app/build/outputs/apk -name '*.apk')
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Tauri-Android-APK
          path: ${{ env.APK_PATH }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.APK_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
